In [1]:
class Employee:
  no_of_employees = 0
  name = ''
  family = ''
  salary = ''
  department = ''
  employees = []
  def __init__(self, name, family, salary, department):
    self.name = name
    self.family = family
    self.salary = salary
    self.department = department
    Employee.no_of_employees += 1
    Employee.employees.append([name, family, salary, department])
  def avg_salary():
    total_sal = sum([employee[2] for employee in Employee.employees])
    return round(total_sal/Employee.no_of_employees,2)

class FulltimeEmployee(Employee):
  pass

#Employee('pranathi', 'reddy', 50000, 'Data')
#Employee('pranay', 'reddy', 75000, 'Development')
#FulltimeEmployee('hemanth', 'reddy', 36000, 'Testing')
# print('Average salary of employees:',Employee.avg_salary())

In [20]:
Employee('Pranathi', 'Reddy', 50000, 'Data')
Employee('Pranay', 'reddy', 75000, 'Development')
FulltimeEmployee('hemanth', 'reddy', 36000, 'Testing')
print('Average salary of employees:',Employee.avg_salary())

Average salary of employees: 53666.67


In [2]:
import numpy as np
vector = np.random.uniform(1,20,20)
arr = vector.reshape(4,5)
maxn = np.amax(arr, axis=1)
print('Original array:\n',arr)
print('\n\nArray after replacing max with 0:\n',np.where(np.isin(arr,maxn), 0, arr))

Original array:
 [[ 1.9476406  11.09428563 14.36061399 12.07998421  4.86979542]
 [ 9.11279533 17.89285271  3.15963173  6.13678219 15.92856326]
 [15.5816091  18.93579979 15.75619821  2.1343613  11.26368966]
 [19.00217855 18.75294408  2.13273741  6.05063951  2.91358831]]


Array after replacing max with 0:
 [[ 1.9476406  11.09428563  0.         12.07998421  4.86979542]
 [ 9.11279533  0.          3.15963173  6.13678219 15.92856326]
 [15.5816091   0.         15.75619821  2.1343613  11.26368966]
 [ 0.         18.75294408  2.13273741  6.05063951  2.91358831]]
